apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  containers:
    - name: hello-app
      image: hello-app:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
